// Styles to improve the UI
export const styles = {
  container: {
    padding: "20px",
    textAlign: "center",
    backgroundColor: "#f9f9f9",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(250px, 1fr))",
    gap: "20px",
    marginTop: "20px",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: "12px",
    boxShadow: "0 4px 10px rgba(0, 0, 0, 0.1)",
    padding: "20px",
    textAlign: "center",
    transition: "transform 0.2s ease, box-shadow 0.2s ease",
  },
  image: {
    width: "150px",
    height: "150px",
    objectFit: "cover",
    borderRadius: "8px",
    marginBottom: "15px",
    transition: "transform 0.3s ease",
  },
  title: {
    fontSize: "18px",
    fontWeight: "600",
    marginBottom: "10px",
    color: "#333",
  },
  price: {
    fontSize: "16px",
    fontWeight: "bold",
    color: "#28a745",
  },
  availability: {
    fontSize: "14px",
    marginBottom: "10px",
  },
  rating: {
    fontSize: "14px",
    marginBottom: "10px",
  },
  stars: {
    color: "#f8c32e",
  },
  button: {
    padding: "8px 20px",
    fontSize: "14px",
    color: "#fff",
    backgroundColor: "#007bff",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    transition: "background-color 0.3s ease",
  },
  modalOverlay: {
    position: "fixed",
    top: "0",
    left: "0",
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  modal: {
    backgroundColor: "#fff",
    padding: "20px",
    borderRadius: "8px",
    width: "80%",
    maxWidth: "800px",
    maxHeight: "80%",
    overflowY: "auto",
    position: "relative",
  },
  modalContent: {
    marginTop: "20px",
    textAlign: "left",
  },
  closeButton: {
    position: "absolute",
    top: "10px",
    right: "10px",
    fontSize: "30px",
    background: "none",
    border: "none",
    cursor: "pointer",
  },
  modalImage: {
    width: "100%",
    height: "auto",
    borderRadius: "8px",
  },
  review: {
    marginBottom: "10px",
    padding: "10px",
    backgroundColor: "#e9ecef",
    borderRadius: "6px",
  },
  heading: {
    fontSize: "2.5rem",
    color: "#333",
    fontWeight: "700",
    marginBottom: "20px",
  },
};
